version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "network-request-checker-qual/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "network-request-checker-qual-android/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
