name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 8, 11 ]
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
        if: github.head_ref != ''
      - name: Push Checkout
        uses: actions/checkout@v4
        if: github.head_ref == ''
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.jdk}}
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Github Environment Setup
        run: |
          owner=${{ github.repository_owner }}
          echo "REPO_SITE=${owner}" >> $GITHUB_ENV
      - name: Checker Build
        run: ./gradlew build
